"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Sidebar from "../../components/layout/Sidebar";import Topbar from "../../components/layout/Topbar";
type Party={id:string;name:string;phone:string;address?:string;gstin?:string;type?:"Customer"|"Supplier"|"Both";openingBalance:number};
const KEY="raghdemo-ledger-parties-v4",money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
export default function PartiesPage(){const [parties,setParties]=useState<Party[]>([]),[q,setQ]=useState(""),[show,setShow]=useState(false),[name,setName]=useState(""),[phone,setPhone]=useState(""),[address,setAddress]=useState(""),[gstin,setGstin]=useState(""),[type,setType]=useState<"Customer"|"Supplier"|"Both">("Customer"),[opening,setOpening]=useState("0");
useEffect(()=>{try{setParties(JSON.parse(localStorage.getItem(KEY)||"[]"));}catch{}},[]);
const visible=useMemo(()=>parties.filter(p=>(p.name+" "+p.phone+" "+(p.gstin||"")).toLowerCase().includes(q.toLowerCase())),[parties,q]);
function save(e:FormEvent){e.preventDefault();if(!name.trim())return;const next=[...parties,{id:crypto.randomUUID(),name:name.trim(),phone:phone.trim(),address:address.trim(),gstin:gstin.trim().toUpperCase(),type,openingBalance:Number(opening)||0}];setParties(next);localStorage.setItem(KEY,JSON.stringify(next));setName("");setPhone("");setAddress("");setGstin("");setOpening("0");setShow(false);}
return <div className="app-shell"><Sidebar/><div className="app-main"><Topbar/><main className="master"><header><div><span>MASTERS</span><h1>Parties</h1><p>Customers and suppliers in one place.</p></div><button onClick={()=>setShow(!show)}>+ Add Party</button></header>
<div className="summary"><div><small>Total Parties</small><b>{parties.length}</b></div><div><small>Opening Receivable</small><b>{money(parties.reduce((s,p)=>s+Math.max(0,p.openingBalance),0))}</b></div></div>
{show&&<form onSubmit={save} className="party-form"><h3>New Party</h3><div className="fields"><label>Party Name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Type<select value={type} onChange={e=>setType(e.target.value as any)}><option>Customer</option><option>Supplier</option><option>Both</option></select></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>GSTIN<input value={gstin} onChange={e=>setGstin(e.target.value)} placeholder="Optional"/></label><label>Opening Balance<input type="number" value={opening} onChange={e=>setOpening(e.target.value)}/></label><label className="wide">Address<input value={address} onChange={e=>setAddress(e.target.value)}/></label></div><div className="form-actions"><button type="button" className="ghost" onClick={()=>setShow(false)}>Cancel</button><button>Save Party</button></div></form>}
<section className="table-card"><div className="table-tools"><input placeholder="Search parties…" value={q} onChange={e=>setQ(e.target.value)}/><span>{visible.length} parties</span></div><div className="scroll"><table><thead><tr><th>Party</th><th>Type</th><th>Phone</th><th>GSTIN</th><th>Opening Balance</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.address||"No address"}</small></td><td><em>{p.type||"Customer"}</em></td><td>{p.phone||"—"}</td><td>{p.gstin||"—"}</td><td className={p.openingBalance>0?"due":""}>{money(p.openingBalance||0)}</td></tr>)}{!visible.length&&<tr><td colSpan={5} className="empty">No parties found.</td></tr>}</tbody></table></div></section>
</main><style jsx global>{css}</style></div></div>}
const css=`*{box-sizing:border-box}body{margin:0;background:#f7f8fa;color:#18212f;font-family:Inter,ui-sans-serif,system-ui}.app-shell{display:flex;min-height:100vh}.app-main{flex:1;min-width:0}.master{padding:30px;max-width:1450px;margin:auto}.master header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.master header span{font-size:10px;font-weight:800;letter-spacing:.14em;color:#be123c}.master h1{margin:4px 0;font-size:27px}.master p{margin:0;color:#778294;font-size:13px}.master button{border:0;border-radius:8px;padding:10px 15px;background:#be123c;color:white;font-weight:700;cursor:pointer}.summary{display:flex;gap:12px;margin-bottom:15px}.summary div{background:white;border:1px solid #e7e9ee;border-radius:11px;padding:14px 18px;min-width:180px}.summary small{display:block;color:#7a8495;font-size:11px}.summary b{display:block;margin-top:5px;font-size:19px}.party-form,.table-card{background:white;border:1px solid #e7e9ee;border-radius:12px;padding:18px;margin-bottom:15px}.party-form h3{margin:0 0 14px}.fields{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.fields label{font-size:11px;font-weight:700;color:#5e6878}.fields input,.fields select,.table-tools input{display:block;width:100%;margin-top:5px;padding:9px 10px;border:1px solid #d7dbe2;border-radius:7px;background:white}.wide{grid-column:span 2}.form-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.form-actions .ghost{background:white;color:#344054;border:1px solid #d7dbe2}.table-tools{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.table-tools input{max-width:330px;margin:0}.table-tools span{font-size:11px;color:#8a94a4}.scroll{overflow:auto}table{width:100%;border-collapse:collapse}th{text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:.05em;color:#7b8595;background:#fafbfc}th,td{padding:11px;border-bottom:1px solid #eef0f3}td{font-size:12px}td small{display:block;color:#8a94a4;margin-top:3px}td em{font-style:normal;background:#f2f4f7;border-radius:20px;padding:4px 8px;font-size:10px}.due{color:#be123c;font-weight:700}.empty{text-align:center!important;padding:30px!important;color:#8a94a4}@media(max-width:800px){.master{padding:18px}.fields{grid-template-columns:1fr}.wide{grid-column:auto}.summary{overflow:auto}.master header{align-items:flex-start;gap:12px}}`;