"use client";
import {useEffect,useState} from "react";
import Sidebar from "../../components/layout/Sidebar";
import Topbar from "../../components/layout/Topbar";

const DB="ledger-local-backups",STORE="snapshots",LAST="raghdemo-ledger-last-backup",WEEK=7*24*60*60*1000;
const settings=[["Business Profile","RaghDemo Traders","Business name, address and GST details"],["Invoice Settings","INV0001","Prefix, numbering and payment terms"],["Taxes & GST","GST enabled · Karnataka","Default tax rates and place of supply"],["Payment Methods","Cash · UPI · Bank","Methods shown while collecting payments"],["Inventory","Low-stock alerts enabled","Stock behaviour and warning thresholds"]];
function openDb(){return new Promise<IDBDatabase>((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:"createdAt"});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function snapshot(){const data:Record<string,string>={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith("raghdemo-ledger-")&&k!==LAST)data[k]=localStorage.getItem(k)||""}const createdAt=new Date().toISOString(),db=await openDb();await new Promise<void>((ok,no)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put({createdAt,formatVersion:1,data});tx.oncomplete=()=>ok();tx.onerror=()=>no(tx.error)});db.close();localStorage.setItem(LAST,createdAt);return createdAt}
async function latest(){const db=await openDb();return new Promise<any>((ok,no)=>{const tx=db.transaction(STORE,"readonly"),r=tx.objectStore(STORE).openCursor(null,"prev");r.onsuccess=()=>{db.close();ok(r.result?.value||null)};r.onerror=()=>{db.close();no(r.error)}})}
export default function Settings(){
 const [last,setLast]=useState("");const [message,setMessage]=useState("");
 useEffect(()=>{let alive=true;(async()=>{try{let t=localStorage.getItem(LAST)||"";if(!t||Date.now()-new Date(t).getTime()>=WEEK)t=await snapshot();if(alive)setLast(t)}catch{if(alive)setMessage("Automatic local backup could not be created.")}})();return()=>{alive=false}},[]);
 async function restore(){try{const b=await latest();if(!b){setMessage("No local backup is available.");return}if(!confirm("Restoring a backup overwrites current Ledger data. Continue?"))return;Object.entries(b.data).forEach(([k,v])=>localStorage.setItem(k,String(v)));setMessage("Backup restored. Reloading…");setTimeout(()=>location.reload(),600)}catch{setMessage("Restore failed.")}}
 async function backupNow(){try{setLast(await snapshot());setMessage("Protected local backup created.")}catch{setMessage("Backup failed.")}}
 return <div style={shell}><Sidebar/><div style={{flex:1}}><Topbar/><main style={main}>
  <div style={head}><div><small style={eye}>CONFIGURATION</small><h1 style={h1}>Settings</h1><p style={muted}>Business preferences, backup and recovery.</p></div></div>
  <div style={notice}><b>Demo company:</b> RaghDemo Traders · Bengaluru, Karnataka · GST billing enabled</div>
  <section style={backupCard}><small style={eye}>AUTOMATIC LOCAL BACKUP</small><h2 style={{margin:"5px 0 6px",fontSize:19}}>Ledger data protection</h2><p style={muted}>Ledger automatically creates a local snapshot when a backup is more than 7 days old. No download prompt is shown. Backups are read-only from normal Ledger screens.</p>
   <div style={backupStatus}><b style={{color:"#067647"}}>Automatic weekly backup enabled</b><small style={small}>{last?`Last protected snapshot: ${new Date(last).toLocaleString()}`:"Preparing first snapshot…"}</small></div>
   <div style={warning}><b>Protected data</b><br/>Deleting browser/site data can permanently remove both Ledger records and local backups. Do not clear Ledger site storage unless another verified backup exists.</div>
   <div style={actions}><button style={button} onClick={backupNow}>Backup Now</button><button style={secondary} onClick={restore}>Restore Latest Backup</button></div>{message&&<div style={result}>{message}</div>}
  </section>
  <div style={grid}>{settings.map(s=><section key={s[0]} style={card}><div style={ico}>⚙</div><div style={{flex:1}}><h3 style={{margin:"0 0 5px",fontSize:15}}>{s[0]}</h3><b style={{fontSize:12}}>{s[1]}</b><p style={muted}>{s[2]}</p></div><button style={edit}>Edit</button></section>)}</div>
 </main></div></div>
}
const shell={display:"flex",minHeight:"100vh",background:"#f7f8fa"} as const,main={padding:30,maxWidth:1200,margin:"auto"} as const,head={display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20} as const,eye={color:"#be123c",fontWeight:800,letterSpacing:".12em"} as const,h1={margin:"4px 0",fontSize:27} as const,muted={margin:"4px 0 0",color:"#778294",fontSize:12} as const,small={display:"block",color:"#778294",fontSize:11,marginTop:5} as const,button={border:0,borderRadius:8,padding:"10px 15px",background:"#be123c",color:"#fff",fontWeight:700,cursor:"pointer"} as const,secondary={border:"1px solid #d7dbe2",borderRadius:8,padding:"9px 14px",background:"#fff",color:"#344054",fontWeight:700,cursor:"pointer"} as const,notice={background:"#fff7ed",border:"1px solid #fed7aa",color:"#9a3412",borderRadius:10,padding:13,marginBottom:15,fontSize:12} as const,backupCard={background:"#fff",border:"1px solid #e7e9ee",borderRadius:12,padding:18,marginBottom:15} as const,backupStatus={background:"#ecfdf3",borderRadius:9,padding:12,marginTop:14} as const,warning={background:"#fffaeb",border:"1px solid #fedf89",color:"#93370d",borderRadius:9,padding:12,marginTop:10,fontSize:12,lineHeight:1.5} as const,actions={display:"flex",gap:9,marginTop:13} as const,result={marginTop:12,fontSize:12,fontWeight:700,color:"#344054"} as const,grid={display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:13} as const,card={background:"#fff",border:"1px solid #e7e9ee",borderRadius:12,padding:17,display:"flex",gap:12,alignItems:"flex-start"} as const,ico={width:34,height:34,borderRadius:9,background:"#f2f4f7",display:"grid",placeItems:"center"} as const,edit={border:"1px solid #d7dbe2",background:"#fff",borderRadius:7,padding:"6px 9px",fontSize:11,fontWeight:700} as const;
