"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";

type Party={id:string;name:string;phone:string;openingBalance:number};
type Item={id:string;name:string;sku:string;unit:string;salePrice:number;purchasePrice:number;taxRate:number;stock:number;lowStock:number};
type Line={id:string;itemId:string;name:string;qty:number;rate:number;taxRate:number;discount:number;unit:string};
type Invoice={id:string;number:string;partyId:string;partyName:string;date:string;item:string;qty:number;rate:number;discount:number;subtotal?:number;tax?:number;items?:Line[];total:number;paid:number;status:"Paid"|"Partial"|"Unpaid"};

const PARTY_KEY="raghdemo-ledger-parties-v4",ITEM_KEY="raghdemo-ledger-items-v5",ENTRY_KEY="raghdemo-ledger-entries-v4",INVOICE_KEY="raghdemo-ledger-invoices-v4";
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2});
const newLine=():Line=>({id:crypto.randomUUID(),itemId:"",name:"",qty:1,rate:0,taxRate:0,discount:0,unit:"PCS"});
const lineValue=(l:Line)=>{const base=Math.max(0,l.qty*l.rate-l.discount);const tax=base*l.taxRate/100;return{base,tax,total:base+tax}};

export default function SaleForm(){
 const [parties,setParties]=useState<Party[]>([]),[items,setItems]=useState<Item[]>([]),[partyId,setPartyId]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10));
 const [lines,setLines]=useState<Line[]>([]),[paid,setPaid]=useState("0"),[message,setMessage]=useState("");
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem(PARTY_KEY)||"[]") as Party[];setParties(p);if(p.length)setPartyId(p[0].id)}catch{}try{setItems(JSON.parse(localStorage.getItem(ITEM_KEY)||"[]"))}catch{}setLines([newLine()])},[]);
 function patch(id:string,v:Partial<Line>){setLines(xs=>xs.map(x=>x.id===id?{...x,...v}:x))}
 function selectItem(id:string,itemId:string){const i=items.find(x=>x.id===itemId);patch(id,i?{itemId,name:i.name,rate:i.salePrice,taxRate:i.taxRate,unit:i.unit}:{itemId:"",name:"",rate:0,taxRate:0})}
 const subtotal=useMemo(()=>lines.reduce((s,l)=>s+lineValue(l).base,0),[lines]),tax=useMemo(()=>lines.reduce((s,l)=>s+lineValue(l).tax,0),[lines]),total=subtotal+tax;
 function save(e:FormEvent){e.preventDefault();setMessage("");const party=parties.find(p=>p.id===partyId),valid=lines.filter(l=>l.itemId&&l.name&&l.qty>0);if(!party||!valid.length||total<=0)return;
  for(const l of valid){const i=items.find(x=>x.id===l.itemId);if(i&&l.qty>i.stock){setMessage("Not enough stock for "+i.name+" (available "+i.stock+" "+i.unit+")");return}}
  const invoices=JSON.parse(localStorage.getItem(INVOICE_KEY)||"[]") as Invoice[];let max=0;invoices.forEach(i=>{max=Math.max(max,Number((i.number||"").replace(/\D/g,""))||0)});const number="INV"+String(max+1).padStart(4,"0"),payment=Math.min(Math.max(Number(paid)||0,0),total);
  const invoice:Invoice={id:crypto.randomUUID(),number,partyId,partyName:party.name,date,item:valid.map(l=>l.name).join(", "),qty:valid.reduce((s,l)=>s+l.qty,0),rate:subtotal,discount:valid.reduce((s,l)=>s+l.discount,0),subtotal,tax,items:valid,total,paid:payment,status:payment>=total?"Paid":payment>0?"Partial":"Unpaid"};
  localStorage.setItem(INVOICE_KEY,JSON.stringify([...invoices,invoice]));
  const entries=JSON.parse(localStorage.getItem(ENTRY_KEY)||"[]");entries.push({id:crypto.randomUUID(),partyId,date,reference:number,description:"Sale Invoice "+number,type:"debit",amount:total});if(payment>0)entries.push({id:crypto.randomUUID(),partyId,date,reference:"PAY-"+number,description:"Payment against "+number,type:"credit",amount:payment});localStorage.setItem(ENTRY_KEY,JSON.stringify(entries));
  const sold:Record<string,number>={};valid.forEach(l=>sold[l.itemId]=(sold[l.itemId]||0)+l.qty);const next=items.map(i=>sold[i.id]?{...i,stock:i.stock-sold[i.id]}:i);setItems(next);localStorage.setItem(ITEM_KEY,JSON.stringify(next));
  setMessage(number+" saved successfully · "+money.format(total-payment)+" due");setLines([newLine()]);setPaid("0");
 }
 return <form onSubmit={save} style={card}>
  <div style={head}><div><div style={eyebrow}>SALES</div><h1 style={{margin:"4px 0",fontSize:25}}>New Sale Invoice</h1><p style={muted}>GST invoice · inventory update · automatic ledger posting</p></div><a href="/sales" style={link}>← Sales</a></div>
  {!parties.length&&<div style={warning}>Add a party from Parties before creating an invoice.</div>}
  <div style={meta}><label style={label}>Customer<select style={field} value={partyId} onChange={e=>setPartyId(e.target.value)} required><option value="">Select party</option>{parties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label style={label}>Invoice Date<input style={field} type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div>
  <div style={sectionHead}><strong>Invoice Items</strong><button type="button" style={secondary} onClick={()=>setLines([...lines,newLine()])}>+ Add Row</button></div>
  <div style={{overflowX:"auto"}}><div style={{minWidth:800}}><div style={columns}>{["Item","Qty","Rate","Discount","GST %","Amount",""].map(x=><span key={x}>{x}</span>)}</div>{lines.map(l=>{const v=lineValue(l);return <div style={row} key={l.id}><select style={compact} value={l.itemId} onChange={e=>selectItem(l.id,e.target.value)}><option value="">Select inventory item</option>{items.map(i=><option key={i.id} value={i.id}>{i.name} · {i.stock} {i.unit}</option>)}</select><input style={compact} type="number" min=".01" step=".01" value={l.qty} onChange={e=>patch(l.id,{qty:Number(e.target.value)})}/><input style={compact} type="number" min="0" step=".01" value={l.rate} onChange={e=>patch(l.id,{rate:Number(e.target.value)})}/><input style={compact} type="number" min="0" step=".01" value={l.discount} onChange={e=>patch(l.id,{discount:Number(e.target.value)})}/><select style={compact} value={l.taxRate} onChange={e=>patch(l.id,{taxRate:Number(e.target.value)})}>{[0,5,12,18,28].map(n=><option key={n} value={n}>{n}</option>)}</select><strong style={{textAlign:"right"}}>{money.format(v.total)}</strong><button type="button" disabled={lines.length===1} onClick={()=>setLines(lines.filter(x=>x.id!==l.id))} style={remove}>×</button></div>})}</div></div>
  {!items.length&&<div style={warning}>Your inventory is empty. Add Items before billing.</div>}
  <div style={bottom}><div><label style={label}>Payment Received Now<input style={field} type="number" min="0" step=".01" value={paid} onChange={e=>setPaid(e.target.value)}/></label><p style={muted}>Any unpaid amount becomes customer receivable.</p></div><div style={totals}><Total label="Taxable Value" value={money.format(subtotal)}/><Total label="GST" value={money.format(tax)}/><Total label="Invoice Total" value={money.format(total)} strong/><Total label="Balance Due" value={money.format(Math.max(0,total-(Number(paid)||0)))}/></div></div>
  <button disabled={!parties.length||!items.length} style={saveButton}>Save Invoice & Update Stock</button>{message&&<div style={message.startsWith("Not enough")?warning:success}>{message}</div>}
 </form>
}
function Total({label:txt,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div style={{display:"flex",justifyContent:"space-between",padding:strong?"10px 0":"4px 0",borderTop:strong?"1px solid #e5e7eb":"none",fontSize:strong?17:12,fontWeight:strong?800:500}}><span>{txt}</span><span>{value}</span></div>}
const card={display:"grid",gap:20,background:"#fff",border:"1px solid #e7e9ee",borderRadius:13,padding:22} as const,head={display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:20} as const,eyebrow={fontSize:10,fontWeight:800,letterSpacing:".14em",color:"#be123c"},muted={margin:0,color:"#7b8595",fontSize:12},link={fontSize:12,color:"#be123c",textDecoration:"none"},meta={display:"grid",gridTemplateColumns:"2fr 1fr",gap:12,padding:14,background:"#f8f9fb",borderRadius:10} as const,label={fontSize:11,fontWeight:700,color:"#5f6979"} as const,field={display:"block",width:"100%",marginTop:5,padding:9,border:"1px solid #d7dbe2",borderRadius:7,background:"#fff",boxSizing:"border-box"} as const,sectionHead={display:"flex",justifyContent:"space-between",alignItems:"center"} as const,secondary={border:"1px solid #d7dbe2",background:"#fff",borderRadius:7,padding:"7px 10px",cursor:"pointer"},columns={display:"grid",gridTemplateColumns:"2.5fr .6fr .9fr .8fr .65fr 1fr 28px",gap:7,padding:"0 3px 6px",fontSize:9,fontWeight:800,color:"#8a94a4",textTransform:"uppercase"} as const,row={display:"grid",gridTemplateColumns:"2.5fr .6fr .9fr .8fr .65fr 1fr 28px",gap:7,alignItems:"center",padding:"8px 0",borderBottom:"1px solid #f0f1f3"} as const,compact={width:"100%",padding:8,border:"1px solid #d7dbe2",borderRadius:7,background:"#fff",boxSizing:"border-box"} as const,remove={border:0,background:"none",fontSize:19,color:"#9aa3b1",cursor:"pointer"},bottom={display:"grid",gridTemplateColumns:"1fr 330px",gap:30,borderTop:"1px solid #eceef1",paddingTop:18} as const,totals={display:"grid",gap:3},saveButton={justifySelf:"end",border:0,background:"#be123c",color:"#fff",borderRadius:8,padding:"11px 18px",fontWeight:800,cursor:"pointer"} as const,warning={padding:11,borderRadius:8,fontSize:12,background:"#fff4e5",color:"#9a5b00"},success={padding:11,borderRadius:8,fontSize:12,background:"#ecfdf3",color:"#067647"};
